# common ========================================================================== #
spring:
  data:
    redis:

      jedis:
        pool:
          enabled: true
          max-active: 8
          max-wait: 10s
      url: ${REDISCLOUD_URL:redis://default:@localhost:6379}
      prefix: ${SPRING_DATA_REDIS_PREFIX:oasis-timeline-autobot:credentials:}
      security:
        key: ${SPRING_DATA_REDIS_SECURITY_KEY:change-me-123456}
        transformation: ${SPRING_DATA_REDIS_SECURITY_TRANSFORMATION:AES}
  groovy:
    template:
      check-template-location: false
  security:
    user:
      name: ${SPRING_ACTUATOR_USERNAME}
      password: ${SPRING_ACTUATOR_PASSWORD}

bluesky:
  public-url: ${BLUESKY_PUBLIC_URL:https://public.api.bsky.app}
  url: ${BLUESKY_URL:https://bsky.social}
  credentials:
    handle: ${BLUESKY_HANDLE}
    password: ${BLUESKY_PASSWORD}

bluesky.context:
    hashtags:
      - Oasis
      - TodayInMusic
      - britpop
      - OTD
    mentions:
      andy_bell: "andybebop.bsky.social"
      brian_cannon: "microdotcreative.bsky.social"
      chemical_brothers: "chemicalbrothers.bsky.social"
      creation_records: "creationrecords.bsky.social"
      john_robb: "johnrobbofficial.bsky.social"
      kevin_cummins: "kcmanc.bsky.social"
      music_canada: "musiccanada.bsky.social"
      noel_gallagher: "noelgallagherlive.bsky.social"
      paul_arthurs: "boneheadspage.bsky.social"
      paul_bonehead_arthurs: "boneheadspage.bsky.social"
      test_mention: "oasistimeline.bsky.social"

post.context:
    uncapitalizeExclusions:
        - Alan
        - Alan McGee
        - All Around the World
        - Andy
        - Beck
        - Brian
        - British
        - Chris
        - Cigarettes & Alcohol
        - Colin
        - Columbia
        - Creation Records
        - Definitely Maybe
        - Don't Believe the Truth
        - Don't Look Back In Anger
        - D'You Know What I Mean?
        - Falling Down
        - Familiar To Millions
        - Gem
        - Go Let It Out
        - Heathen Chemistry
        - I'm Outta Time
        - Kevin
        - Let There Be Love
        - Liam
        - Live Forever
        - Lord Don't Slow Me Down
        - Lyla
        - Maggie
        - Mark
        - Michael
        - Music Canada
        - Noel
        - Oasis
        - Owen
        - Paul
        - Phil
        - Robbie
        - Roll With It
        - Scott
        - Shakermaker
        - Some Might Say
        - Songbird
        - Sony
        - Stand By Me
        - Standing on the Shoulder of Giants
        - Stop Crying Your Hear Out
        - Stop The Clocks
        - Sunday Morning Call
        - Supersonic
        - The Hindu Times
        - The Importance of Being Idle
        - The Masterplan
        - The Shock of the Lightning
        - Uptown Magazine
        - Whatever
        - Who Feels Love?
        - Wonderwall
        - Zak

tweet.context:
    hashtags:
      - Oasis
      - TodayInMusic
      - britpop
      - OTD
    mentions:
      abbey_road_studios: "AbbeyRoad"
      alex_james: "alexjameshq"
      andy_bell: "Andybebop"
      anita_heyret: "Neetsy77"
      beck: "Beck"
      black_crowes: "theblackcrowes"
      blur: "blurofficial"
      brian_cannon: "microdotcreativ"
      british_phonographic_industry: "bpi_music"
      cast: "castofficial"
      chemical_brothers: "chembros"
      chris_evans: "achrisevans"
      colin_gem_archer: "gemarcherbe"
      creation_records: "creationrecords"
      davina_mcCall: "ThisisDavina"
      death_in_veags: "DIVofficial"
      epic_records: "Epic_Records"
      evan_dando: "evan_dando"
      gem_archer: "gemarcherbe"
      graham_lambert: "InspiralGraham"
      jill_furmanovsky: "jillfurmanovsky"
      james_walsh: "jamesstarsailor"
      jo_whiley: "jowhiley"
      john_harris: "johnharris1969"
      john_robb: "johnrobb77"
      johnny_depp: "JohnJohnnydepp"
      johnny_marr: "Johnny_Marr"
      kevin_cummins: "KCMANC"
      liam_gallagher: "liamGallagher"
      mark_spike_stent: "markspikestent"
      mat_whitecross: "matwhitecross"
      matt_deighton: "deighton_matt"
      matthew_perry: "MatthewPerry"
      michael_spencer_jones: "msj_photo"
      music_bank: "sarmmusicbank"
      music_canada: "music_canada"
      nic_goffey: "ngoffey"
      nigel_dick: "nigeldick"
      noel_gallagher: "noelgallagher"
      patsy_kensit: "patsy_kensit"
      paul_arthurs: "boneheadspage"
      paul_bonehead_arthurs: "boneheadspage"
      paul_weller: "paulwellerHQ"
      pete_doherty: "petedoherty"
      recording_industry_association_of_america: "RIAA"
      richard_ashcroft: "richardashcroft"
      richard_fearless: "RichardFearless"
      robbie_williams: "robbiewilliams"
      robert_carlyle: "robertcarlyle_"
      rockfield_studios: "rockfieldstudio"
      rhys_ifans: "official_ifans"
      simon_emmett: "simon_emmett"
      simon_halfon: "halfon"
      steve_cradock: "stevecradock"
      steve_lamacq: "steve_lamacq"
      steve_white: "drummerwhitey"
      test_mention: "OasisTimeline"
      the_roundhouse: "RoundhouseLDN"
      the_verve: "genuineverve"
      tim_lovejoy: "timlovejoy"
      tony_mcCarroll: "TonyMcCarrolls"

logging:
  level:
    com.jdpgrailsdev: INFO
    com.twitter.clientlib.auth: TRACE
    org.eclipse.jetty: ERROR
    org.springframework: INFO 

management:
  endpoints:
    web.exposure.include: "*"
    access:
      default: "unrestricted"
  endpoint:
    health:
      show-details: "always"
      sensitive: false
  info:
    os:
      enabled: true
    java:
      enabled: true

oauth2:
  pkce:
    challenge: ${OAUTH2_PKCE_CHALLENGE:challenge}
  twitter:
    scopes: ${OAUTH2_TWITTER_SCOPES:offline.access tweet.read tweet.write users.read}

server:
  base-url: ${SERVER_BASE_URL:http://localhost:8080}
  jetty:
    max-queue-capacity: 1000
  shutdown: "graceful"
---

# development ========================================================================== #
spring.config.activate.on-profile: development
    
logging:        
  level:
    com.jdpgrailsdev: DEBUG
    com.newrelic.telemetry: OFF
    io.micrometer.newrelic: OFF  
---    

# test ========================================================================== #
spring:
  main:
    allow-bean-definition-overriding: true
  config.activate.on-profile: test
  security:
    user:
      name: "test"
      password: "test"
    
logging:        
  level:
    com.jdpgrailsdev: DEBUG
    com.newrelic.telemetry: OFF
    com.twitter.clientlib.auth: OFF
    io.micrometer.newrelic: OFF