# common ========================================================================== #
spring:
  groovy:
    template:
      check-template-location: false
  security:
    user:
      name: ${SPRING_ACTUATOR_USERNAME}
      password: ${SPRING_ACTUATOR_PASSWORD}
      
description:
  uncapitalize:
    exclusions: "Noel,Liam,Oasis,Whatever,All Around the World,Songbird,Go Let It Out,Don't Look Back In Anger,Mark,Standing on the Shoulder of Giants,Falling Down,D'You Know What I Mean?,Owen,British,Paul,Supersonic,The Hindu Times,Who Feels Love?,Some Might Say,Alan,Roll With It,Zak,Chris,The Shock of the Lightning,Go Let It Out,Lyla,Definitely Maybe,Don't Believe the Truth,Shakermaker,Stop Crying Your Hear Out,Roll With It,Heathen Chemistry,Sunday Morning Call,Phil,Wonderwall,Live Forever,Cigarettes & Alcohol,The Importance of Being Idle,Creation Records,Stand By Me,Scott,Michael,Uptown Magazine,Lord Don't Slow Me Down,Colin,Gem,Andy,The Masterplan,The British Phonographic Institute,The Recording Industry Association of America,Familiar To Millions,Stop The Clocks,Alan,Let There Be Love,I'm Outta Time"
      
logging:
  level:
    com.jdpgrailsdev: INFO
    org.eclipse.jetty: ERROR
    org.springframework: INFO 
    
    
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: "*"
  endpoint:
    health:
      show-details: "always"
      sensitive: false           
---

# development ========================================================================== #
spring:
  profiles: development
    
logging:        
  level:
    com.jdpgrailsdev: DEBUG
    com.newrelic.telemetry: OFF
    io.micrometer.newrelic: OFF  
---    

# test ========================================================================== #
spring:
  main:
    allow-bean-definition-overriding: true
  profiles: test
    
logging:        
  level:
    com.jdpgrailsdev: DEBUG
    com.newrelic.telemetry: OFF
    io.micrometer.newrelic: OFF