name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:      
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Test
        run: ./gradlew clean check --stacktrace --no-daemon
     
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:      
          java-version: 21
          distribution: temurin
          cache: gradle
          
      - name: Build
        run: ./gradlew clean build --stacktrace -x test -x intTest --no-daemon
        
      - name: Tag Release
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          body: ${{ steps.tag_version.outputs.changelog }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            web/build/dist/oasis-timeline-web.tar
            autobot/build/libs/oasis-timeline-autobot.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:      
          java-version: 21
          distribution: temurin

      - name: Deploy
        env:
          GRGIT_USER: ${{ secrets.WEB_API_KEY }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          NEW_RELIC_APPLICATION_ID: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          NEW_RELIC_REST_API_KEY: ${{ secrets.NEW_RELIC_REST_API_KEY }}
        run: ./gradlew build publish --stacktrace -x test -x intTest -PnewRelicRestApiKey=${NEW_RELIC_REST_API_KEY} -PnewRelicApplicationId=${NEW_RELIC_APPLICATION_ID}
