name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:      
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Test
        run: ./gradlew clean check --stacktrace --no-daemon
     
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:      
          java-version: 17
          distribution: temurin
          cache: gradle
          
      - name: Build
        run: ./gradlew clean build --stacktrace -x test -x intTest --no-daemon
        
      - name: Tag Release
        uses: mathieudutour/github-tag-action@v5.1
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.tag_version.outputs.changelog }}
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            web/build/dist/oasis-timeline-web.tar
            autobot/build/libs/oasis-timeline-autobot.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: ./gradlew clean :oasis-timeline-autobot:buildDockerImage -x test -x intTest --no-daemon

      - name: Push Docker Image
        uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          image_name: oasis-timeline-autobot
          image_tag: latest
          push_only: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2        

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:      
          java-version: 17
          distribution: temurin

      - name: Deploy
        env:
          GRGIT_USER: ${{ secrets.WEB_API_KEY }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          NEW_RELIC_APPLICATION_ID: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          NEW_RELIC_REST_API_KEY: ${{ secrets.NEW_RELIC_REST_API_KEY }}
        run: ./gradlew build publish --stacktrace -x test -x intTest -PnewRelicRestApiKey=${NEW_RELIC_REST_API_KEY} -PnewRelicApplicationId=${NEW_RELIC_APPLICATION_ID}
