name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:      
          java-version: 21
          distribution: temurin

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Test
        run: ./gradlew clean check
     
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:      
          java-version: 21
          distribution: temurin

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      - name: Build
        run: ./gradlew clean build -x test -x intTest
